require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RequisitometrologicosController do

  # This should return the minimal set of attributes required to create a valid
  # Requisitometrologico. As you add validations to Requisitometrologico, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome_do_requisito" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequisitometrologicosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all requisitometrologicos as @requisitometrologicos" do
      requisitometrologico = Requisitometrologico.create! valid_attributes
      get :index, {}, valid_session
      assigns(:requisitometrologicos).should eq([requisitometrologico])
    end
  end

  describe "GET show" do
    it "assigns the requested requisitometrologico as @requisitometrologico" do
      requisitometrologico = Requisitometrologico.create! valid_attributes
      get :show, {:id => requisitometrologico.to_param}, valid_session
      assigns(:requisitometrologico).should eq(requisitometrologico)
    end
  end

  describe "GET new" do
    it "assigns a new requisitometrologico as @requisitometrologico" do
      get :new, {}, valid_session
      assigns(:requisitometrologico).should be_a_new(Requisitometrologico)
    end
  end

  describe "GET edit" do
    it "assigns the requested requisitometrologico as @requisitometrologico" do
      requisitometrologico = Requisitometrologico.create! valid_attributes
      get :edit, {:id => requisitometrologico.to_param}, valid_session
      assigns(:requisitometrologico).should eq(requisitometrologico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Requisitometrologico" do
        expect {
          post :create, {:requisitometrologico => valid_attributes}, valid_session
        }.to change(Requisitometrologico, :count).by(1)
      end

      it "assigns a newly created requisitometrologico as @requisitometrologico" do
        post :create, {:requisitometrologico => valid_attributes}, valid_session
        assigns(:requisitometrologico).should be_a(Requisitometrologico)
        assigns(:requisitometrologico).should be_persisted
      end

      it "redirects to the created requisitometrologico" do
        post :create, {:requisitometrologico => valid_attributes}, valid_session
        response.should redirect_to(Requisitometrologico.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved requisitometrologico as @requisitometrologico" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisitometrologico.any_instance.stub(:save).and_return(false)
        post :create, {:requisitometrologico => { "nome_do_requisito" => "invalid value" }}, valid_session
        assigns(:requisitometrologico).should be_a_new(Requisitometrologico)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Requisitometrologico.any_instance.stub(:save).and_return(false)
        post :create, {:requisitometrologico => { "nome_do_requisito" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested requisitometrologico" do
        requisitometrologico = Requisitometrologico.create! valid_attributes
        # Assuming there are no other requisitometrologicos in the database, this
        # specifies that the Requisitometrologico created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Requisitometrologico.any_instance.should_receive(:update).with({ "nome_do_requisito" => "" })
        put :update, {:id => requisitometrologico.to_param, :requisitometrologico => { "nome_do_requisito" => "" }}, valid_session
      end

      it "assigns the requested requisitometrologico as @requisitometrologico" do
        requisitometrologico = Requisitometrologico.create! valid_attributes
        put :update, {:id => requisitometrologico.to_param, :requisitometrologico => valid_attributes}, valid_session
        assigns(:requisitometrologico).should eq(requisitometrologico)
      end

      it "redirects to the requisitometrologico" do
        requisitometrologico = Requisitometrologico.create! valid_attributes
        put :update, {:id => requisitometrologico.to_param, :requisitometrologico => valid_attributes}, valid_session
        response.should redirect_to(requisitometrologico)
      end
    end

    describe "with invalid params" do
      it "assigns the requisitometrologico as @requisitometrologico" do
        requisitometrologico = Requisitometrologico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisitometrologico.any_instance.stub(:save).and_return(false)
        put :update, {:id => requisitometrologico.to_param, :requisitometrologico => { "nome_do_requisito" => "invalid value" }}, valid_session
        assigns(:requisitometrologico).should eq(requisitometrologico)
      end

      it "re-renders the 'edit' template" do
        requisitometrologico = Requisitometrologico.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Requisitometrologico.any_instance.stub(:save).and_return(false)
        put :update, {:id => requisitometrologico.to_param, :requisitometrologico => { "nome_do_requisito" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested requisitometrologico" do
      requisitometrologico = Requisitometrologico.create! valid_attributes
      expect {
        delete :destroy, {:id => requisitometrologico.to_param}, valid_session
      }.to change(Requisitometrologico, :count).by(-1)
    end

    it "redirects to the requisitometrologicos list" do
      requisitometrologico = Requisitometrologico.create! valid_attributes
      delete :destroy, {:id => requisitometrologico.to_param}, valid_session
      response.should redirect_to(requisitometrologicos_url)
    end
  end

end
